name: Dinit Regular CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/regular_ci.yml'
      - 'configure'
      - 'build/**'
      - 'configs/**'
      - 'dasynq/**'
      - 'src/**'
      - '**/Makefile'
      - '!build/mconfig.mesontemplate'
      - '!build/includes/README'
      - '!**/meson.build'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/regular_ci.yml'
      - 'configure'
      - 'build/**'
      - 'configs/**'
      - 'dasynq/**'
      - 'src/**'
      - '**/Makefile'
      - '!build/mconfig.mesontemplate'
      - '!build/includes/README'
      - '!**/meson.build'
  workflow_dispatch:

jobs:

#
#  Debian-bookworm_build:
#
#    runs-on: ubuntu-24.04
#    container:
#      image: debian:bookworm
#    strategy:
#      fail-fast: false # Upload src/igr-tests/*/output/* files in igr-tests
#      matrix:
#        include:
#          - arch: 'amd64'
#          - arch: 'i386'

#    steps:
#    - uses: actions/checkout@v4
#    - name: Add i386 repositories
#      if: ${{ matrix.arch == 'i386' }}
#      run: dpkg --add-architecture i386
#    - name: Getting dependencies (amd64)
#      if: ${{ matrix.arch == 'amd64' }}
#      run: |
#        apt-get update
#        DEBIAN_FRONTEND=noninteractive apt-get install g++ make m4 libcap-dev file -y
#    - name: Getting dependencies (i386)
#      if: ${{ matrix.arch == 'i386' }}
#      run: |
#        apt-get update
#        DEBIAN_FRONTEND=noninteractive apt-get install gcc:i386 make:i386 m4:i386 g++:i386 libcap-dev:i386 file -y
#    - name: Print g++ architecture and version
#      run: |
#        g++ -dumpmachine
#        g++ --version
#    - name: Build
#      run: make CXXFLAGS_EXTRA=-D_GLIBCXX_DEBUG TEST_CXXFLAGS_EXTRA=-D_GLIBCXX_DEBUG
#    - name: Print dinit executable file architecture
#      run: file ./src/dinit
#    - name: Unit tests
#      run: make check
#    - name: Integration tests
#      run: make check-igr
#    - name: Upload igr-tests output file(s) on failure
#      uses: actions/upload-artifact@v4.3.2
#      if: failure()
#      with:
#          name: igr-tests_output
#          path: src/igr-tests/*/output/*

#  MacOS-latest_build:

#    runs-on: macos-latest
#    strategy:
#      fail-fast: false # Upload src/igr-tests/*/output/* files in igr-tests
#      matrix:
#        include:
#          - arch: 'aarch64'

#    steps:
#    - uses: actions/checkout@v4
#    - name: Print g++ architecture and version
#      run: |
#        g++ -dumpmachine
#        g++ --version
#    - name: Build
#      run: make
#    - name: Print dinit executable file architecture
#      run: file ./src/dinit
#    - name: Unit tests
#      run: make check
#    - name: Integration tests
#      run: make check-igr
#    - name: Upload igr-tests output file(s) on failure
#      uses: actions/upload-artifact@v4.3.2
#      if: failure()
#      with:
#          name: igr-tests_output
#          path: src/igr-tests/*/output/*

#  Alpine-latest_build:

#    runs-on: ubuntu-24.04
#    container:
#      image: alpine:latest
#    strategy:
#      fail-fast: false # Upload src/igr-tests/*/output/* files in igr-tests
#      matrix:
#        include:
#          - arch: 'amd64'

#    steps:
#    - uses: actions/checkout@v4
#    - name: Getting dependencies
#      run: |
#        apk update
#        apk add make g++ m4 file libcap-dev
#    - name: Print g++ architecture and version
#      run: |
#        g++ -dumpmachine
#        g++ --version
#    - name: Build
#      run: make
#    - name: Print dinit executable file architecture
#      run: file ./src/dinit
#    - name: Unit tests
#      run: make check
#    - name: Integration tests
#      run: make check-igr
#    - name: Upload igr-tests output file(s) on failure
#      uses: actions/upload-artifact@v4.3.2
#      if: failure()
#      with:
#          name: igr-tests_output
#          path: src/igr-tests/*/output/*

  FreeBSD-15-with-compiler-hardening_build:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: cpa.sh {0}
    env:
      FREEBSD_VERSION: 15.1-RELEASE
    strategy:
      fail-fast: false # Upload src/igr-tests/*/output/* files in igr-tests
      matrix:
        include:
          - arch: 'amd64'

    steps:
    - uses: actions/checkout@v6
    - name: Getting FreeBSD BASIC-CI image
      run: |
        wget -nv https://download.freebsd.org/releases/CI-IMAGES/${FREEBSD_VERSION}/amd64/Latest/FreeBSD-${FREEBSD_VERSION}-amd64-BASIC-CI-ufs.raw.xz
        unxz FreeBSD-${FREEBSD_VERSION}-amd64-BASIC-CI-ufs.raw.xz
    - name: Mount FreeBSD BASIC-CI image
      run: |
        LO_DEVICE=$(sudo losetup --find --show --partscan FreeBSD-${FREEBSD_VERSION}-amd64-BASIC-CI-ufs.raw)
        sudo modprobe ufs
        lsblk
        #mkdir freebsd_image
        #sudo mount -t ufs -o ufstype=ufs2 ${LO_DEVICE} freebsd_image/
    - name: List directory
      run: ls -lah freebsd_image/
    - name: dmesg
      if: failure()
      run: sudo dmesg
